name: Run Check tests for C code

on: [push]

jobs:
  build:
    name: Running tests & Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y gcc tree check curl
      - name: Run testing script
        run: chmod +x run_tests.sh && ./run_tests.sh > results
      - name: Export env
        run: echo "test_passed=$(grep '100%' -o results | wc -l)" >> $GITHUB_ENV
      - name: print TEST env
        run: echo "${{env.test_passed}}"
      - name: Send test result
        if: env.test_passed == '4'
        uses: langroodi/doxygenize@v1
        with:
          ghpagesbranch: main
          ghpagesdir: ./docs/